spring.application.name=usuarios-service


# MongoDB configuración directa (sin URI)
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=schedulemanagementhumboldtusersdbvsc

# Logging de Spring Security
logging.level.org.springframework.security=DEBUG