spring.application.name=usuarios-service


# MongoDB configuración directa (sin URI)
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=schedulemanagementhumboldtusersdbvsc
spring.data.mongodb.auto-index-creation=true

# Envío de correos para recuperación de contraseña
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=53ef4a0df345ed
spring.mail.password=85cb6111fbeeb2
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Logging de Spring Security
logging.level.org.springframework.security=DEBUG