spring.application.name=usuarios-service


# MongoDB configuración directa (sin URI)
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=schedulemanagementhumboldtusersdbvsc
spring.data.mongodb.auto-index-creation=true

# Configuración para Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=juan.warfare100@gmail.com
spring.mail.password=czwwwsezejgkctzs

# Propiedades SMTP adicionales
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Logging de Spring Security
logging.level.org.springframework.security=DEBUG